-- Booking links: direct payment links generated by transporters for clients
CREATE TABLE IF NOT EXISTS booking_links (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  token UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
  company_id UUID NOT NULL REFERENCES companies(id),
  vehicle_id UUID NOT NULL REFERENCES vehicles(id),
  pickup_city TEXT NOT NULL,
  dropoff_city TEXT NOT NULL,
  departure_date DATE NOT NULL,
  return_date DATE,
  passengers INTEGER NOT NULL DEFAULT 1,
  total_price NUMERIC(10,2) NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'used', 'expired')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days')
);

ALTER TABLE booking_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view active booking links" ON booking_links
  FOR SELECT USING (status = 'active');

CREATE POLICY "Transporters can create booking links" ON booking_links
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM companies WHERE id = company_id AND owner_id = auth.uid())
  );

CREATE POLICY "Transporters can update own links" ON booking_links
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM companies WHERE id = company_id AND owner_id = auth.uid())
  );
